#pragma once
#include <windows.h>
#include <WindowsX.h>
#include <dxgi1_4.h>
#include <d3d12.h>
#include <D3Dcompiler.h>
#include <DirectXMath.h>
#include <DirectXColors.h>
#include <d3d12sdklayers.h>
#include <comdef.h>
#include <cassert>
#include <winerror.h>
#include <string>
#include <vector>
#include "framework.h"
#include "d3dx12.h"
#include "D3DUtils.h"
#include "GameTime.h"